name: flutter_djolis
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.37+37

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3

  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  firebase_remote_config: ^6.1.1
  firebase_analytics: ^12.0.4
  firebase_messaging: ^16.0.4
  firebase_auth: ^6.1.2

  flex_color_scheme: ^8.3.1
  device_info_plus: ^12.2.0
  intl: ^0.20.2
  uuid: ^4.4.0
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3
  mime: ^2.0.0
  permission_handler: ^12.0.1
  flutter_slidable: ^4.0.3
  cached_network_image: ^3.3.1
  http: ^1.1.0
  flutter_local_notifications: ^19.5.0
  overlay_support: ^2.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  animated_toggle_switch: ^0.8.2
#  sms_autodetect: ^1.1.0
  qr_flutter: ^4.1.0
  easy_image_viewer: ^1.5.1
  share_plus: ^12.0.0
  video_player: ^2.9.2
  package_info_plus: ^9.0.0
  no_screenshot: ^0.3.1
  confirm_dialog: ^1.0.4
  appmetrica_plugin: ^3.1.0
  star_menu: ^4.0.1
  select_dialog: ^2.0.2
  location: ^8.0.1
  google_maps_flutter: ^2.9.0
  carousel_slider: ^5.1.1


  flutter_localizations:
    sdk: flutter
  extended_masked_text: ^3.0.1
  awesome_dialog: ^3.2.1
  image_picker: ^1.1.2
  teledart: ^0.6.1

dependency_overrides:
    sqflite: 2.3.3+1
#    sqflite_android: 2.3.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
     - lang/uz.json
     - lang/ru.json
     - lang/en.json
     - lang/ar.json

  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter-Bold.ttf
         - asset: assets/fonts/Inter-Regular.ttf
         - asset: assets/fonts/Inter-Medium.ttf
         - asset: assets/fonts/Inter-Light.ttf

